### ISSUE TITLE
Fail to run `azd up` in Codespaces and DevContainers

### ISSUE THREAD

**Issue by Yionse** [Azure-Samples/hello-azd#1]
**Describe the issue:**
When running `azd up`, the following error occurs:
![image](https://github.com/user-attachments/assets/21ab1d20-7144-4831-966c-b84b22adb0db)

**Repro Steps:**
1. Open in GitHub Codespaces.
2. Run `azd auth login`.
3. Run `azd up`.

**Environment:**
- azd version 1.10.1 (commit 31409a33266fb4a5fdbb644bc83988e725d6c7c9)
- OS: Codespaces, DevContainers

**Expected behavior:**
Run `azd up` successful.

@alexwolfmsft and @hemarina for notification.

**Comment by jerryshia** [comment]
This issue has been resolved.
